### PR TITLE
Add @A001519

### LINKED ISSUE #83: A001519 / fibonacci-bisection
[A001519 / a(n) = 3*a(n-1) - a(n-2), with a(0) = a(1) = 1.](https://oeis.org/A001519)

The sequence is not implemented yet.

<code>
1 1 2 5 13 34 89 233 610 1597 4181 10946 28657 75025 196418 514229 1346269 3524578 9227465 24157817 63245986 165580141 433494437 1134903170 2971215073 7778742049 20365011074 53316291173 139583862445 365435296162 956722026041
</code>

### PR DESCRIPTION
**Pull request by MasterDuke17**
Fixes #83

### CODE REVIEW

**Comment by AlexDaniel** [comment]
Wouldn't it be easier with a sequence operator?
```
our @A001519 is export = 1, 1, -> $n2, $n1 { 3 * $n1 - $n2 } ... *;
```

**Comment by AlexDaniel** [comment]
Same in this PR: https://github.com/ajs/perl6-Math-Sequences/pull/128 (looks like it only depends on two previous elements)

**Comment by MasterDuke17** [comment]
Yep. I've been enamored with multis recently and reaching for them first for everything.

**Comment by MasterDuke17** [comment]
Updated.

**Comment by AlexDaniel** [comment]
Same coming for https://github.com/ajs/perl6-Math-Sequences/pull/128/files I assume, yes? :)

Thanks!

**Pull request merged**
